await page.goto('https://dev-app.carbonregistry.com/login?redirectedFrom=%2F');
await page.getByRole('textbox', { name: 'Email' }).click();
await page.getByRole('textbox', { name: 'Email' }).fill('aninday.mondal+automation@kreeti.com');
await page.getByRole('textbox', { name: 'Email' }).press('Tab');
await page.getByRole('textbox', { name: 'Password' }).fill('Aninday@2002');
await page.getByRole('textbox', { name: 'Password' }).press('Enter');
await page.getByRole('button', { name: 'Sign in' }).click();
await page.getByRole('button', { name: 'Create Organization' }).click();
await page.getByRole('textbox', { name: 'Company Inc.' }).click();
await page.getByRole('textbox', { name: 'Company Inc.' }).fill('test_automation');
await page.getByRole('textbox', { name: 'www.website.com' }).click();
await page.getByRole('textbox', { name: 'www.website.com' }).fill('www.automation.com');
await page.getByRole('button', { name: 'File Upload' }).click();
await page.getByRole('button', { name: 'File Upload' }).setInputFiles('Aninday.png');
await page.getByRole('button', { name: 'Upload Original Image' }).click();
await page.getByRole('checkbox', { name: 'Please accept the' }).click();
await page.getByRole('button', { name: 'Create Organization' }).click();
await page.goto('https://dev-app.carbonregistry.com/organizations/78b80d63-5d55-4bbe-8d7c-4bcc26398927');
await page.getByRole('checkbox', { name: 'Project Proponent Paid' }).click();
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByText('Monthly (Card)').click();
const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Add Payment Method' }).click();
  const page1 = await page1Promise;
await page1.locator('[data-test="email"]').click();
await page1.locator('[data-test="email"]').fill('aninday.mondal+automation@kreeti.com');
await page1.locator('[data-test="email"]').press('Enter');
await page1.locator('iframe[name="Airwallex dropIn element iframe"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card number' }).click();
await page1.locator('iframe[name="Airwallex dropIn element iframe"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card number' }).fill('4035 5010 0000 0008    ');
await page1.locator('iframe[name="Airwallex dropIn element iframe"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card expiration date' }).click();
await page1.locator('iframe[name="Airwallex dropIn element iframe"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card expiration date' }).fill('01 / 35');
await page1.locator('iframe[name="Airwallex dropIn element iframe"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card CVC/CVV/' }).click();
await page1.locator('iframe[name="Airwallex dropIn element iframe"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card CVC/CVV/' }).fill('000 ');
await page1.locator('iframe[name="Airwallex dropIn element iframe"]').contentFrame().getByRole('textbox', { name: 'Pin' }).click();
await page1.locator('iframe[name="Airwallex dropIn element iframe"]').contentFrame().getByRole('textbox', { name: 'Pin' }).fill('700001');
await page1.locator('iframe[name="Airwallex dropIn element iframe"]').contentFrame().getByRole('button', { name: 'Save card' }).click();
await page1.goto('https://dev-app.carbonregistry.com/organizations/78b80d63-5d55-4bbe-8d7c-4bcc26398927');
await page1.getByRole('button', { name: 'Continue' }).click();

await page1.getByRole('radio').nth(1).click();
await page1.getByRole('tab', { name: 'Invoice' }).click();
await page1.getByRole('button', { name: 'Select country' }).click();
await page1.getByRole('option', { name: 'Albania' }).click();
await page1.getByRole('button', { name: 'Continue' }).click();